name: Deploy features branches to nonproduction bucket

on: 
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-f58da8399c5675dcff73f8e22-nonprodbucket-16cpu6bqup7i5
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name:
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: 
          npm ci
      - name: build site
        run: 
          npm run build
      - name: deploy files to bucket
        run: ls
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive